site_name: HIST3814o Crafting Digital History
theme: readthedocs
theme_dir: "theme"
site_url: http://craftingdigitalhistory.ca
site_description: All course materials crafted ex novo by Shawn Graham are provided with an open source license as Markdown files. I welcome contributions in the form of pull requests.
site_author: Shawn Graham
repo_url: https://github.com/shawngraham/dhworkbook/tree/gh-pages
# Below is the tota11y accessibility tool that adds a small button
# on the bottom left of the screen. FOR TESTING PURPOSES ONLY.
# To enable, download file (https://github.com/Khan/tota11y/releases/download/0.1.3/tota11y.min.js) 
# and add file to /docs/js/ folder.
# Uncomment below to enable.
# extra_javascript:
  # - 'js/tota11y.min.js'
extra_css:
  - 'css/extra.css'
pages:
- Home: 'index.md'
- Getting Started: 'introduction/crafting-digital-history.md'
- 1. Open Access Research:
    - 'Why you should be open': 'module-1/Open-Access-Research.md'
    - 'Exercises': 'module-1/Exercises.md'
- 2. Finding Data:
    - 'How do we find data?': 'module-2/Finding Data.md'
    - 'Exercises': 'module-2/Exercises.md'
- 3. Fixing Data:
    - 'Data is messy': 'module-3/Wrangling Data.md'
    - 'Exercises': 'module-3/Exercises.md'
- 4. Analysis:
    - 'Seeing Patterns': 'module-4/Seeing Patterns.md'
    - 'Exercises': 'module-4/Exercises.md'
- 5. Visualization:
    - 'Communicating your Findings': 'module-5/Humanities Visualization.md'
    - 'Capstone Exercise': 'module-5/Exercises.md'
- 6. Final Thoughts: 'conclusion/Conclusion.md'
- Appendices:
    - 'Text Encoding Initiative': 'supporting materials/tei.md'
    - 'Git in RStudio': 'supporting materials/git-rstudio.md'
    - 'Introduction to Regular Expressions (regex)': 'supporting materials/regex.md'
    - 'Regex & the Republic of Texas': 'supporting materials/regexex.md'
    - 'Open Refine': 'supporting materials/open-refine.md'
    - 'Stanford Named Entity Recognizer': 'supporting materials/ner.md'
    - 'Going further with regex': 'supporting materials/regex-ner.md'
    - 'Quick intro to R': 'supporting materials/quick-intro-r.md'
    - 'Choose Your Own Adventure': 'supporting materials/cyoa.txt.md'
    - 'Geoparsing with Python': 'supporting materials/geoparsing-w-python.txt.md'
    - 'Glitch': 'supporting materials/glitch.md'
    - 'Social Network Analysis with Gephi': 'supporting materials/gephi.txt.md'
    - 'Graphing the Net': 'supporting materials/graphing-the-net.txt.md'
    - 'Topic Modeling, DH Box': 'supporting materials/topicmodel-r-dhbox.md'
    - 'Topic Modeling, Local': 'supporting materials/topicmodel-r-yourmachine.md'
    - 'Network visualization with igraph': 'supporting materials/netviz.md'
    - 'Inkscape': 'supporting materials/inkscape.md'
    - 'GitHub Pages': 'supporting materials/gh-pages.md'
    - 'Leaflet': 'supporting materials/leaflet.txt.md'
